// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLSandboxML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public string Comment { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public string Value { get; set; }


    }
}
